export const weatherImages = {
    '약간 흐림': require('../assets/images/partlycloudy.png'),
    '가벼운 이슬비': require('../assets/images/moderaterain.png'),
    '가벼운 소나기': require('../assets/images/moderaterain.png'),
    '근처 곳곳에 비': require('../assets/images/moderaterain.png'),
    '맑음': require('../assets/images/sun.png'),
    '대체로 맑음': require('../assets/images/sun.png'),
    '흐린': require('../assets/images/cloud.png'),
    '구름낀': require('../assets/images/cloud.png'),
    '가벼운 비': require('../assets/images/moderaterain.png'),
    '보통 비': require('../assets/images/moderaterain.png'),
    '폭우': require('../assets/images/heavyrain.png'),
    '때떄로 큰 비': require('../assets/images/heavyrain.png'),
    '보통 또는 강한 비': require('../assets/images/heavyrain.png'),
    '보통 또는 폭우': require('../assets/images/heavyrain.png'),
    '천둥을 동반한 보통 또는 폭우': require('../assets/images/heavyrain.png'),
    '다른': require('../assets/images/moderaterain.png'),   
}